name: Cross Compile to FreeBSD AArch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: sigoden/dufs

    - name: Install Rust
      run: rustup update nightly && rustup default nightly
       
    - name: Install cross-compilation tools
      uses: taiki-e/setup-cross-toolchain-action@v1
      with:
        target: aarch64-unknown-freebsd@14
    - run: CFLAGS=-Wno-implicit-function-declaration cargo build --release --verbose -Z build-std

    - name: Upload compiled artifact
      uses: actions/upload-artifact@v3
      with:
        name: freebsd-aarch64-build
        path: target/aarch64-unknown-freebsd/release/dufs
